version: '3.7'
services:
  frontend:
    image: node:21-alpine3.18
    tty: true
    volumes:
      - ./full-stack-frontend:/home/node/app
    ports:
      - 5173:5173
    working_dir: /home/node/app
    command: /bin/sh -c "yarn install && yarn dev"
