version: '3.7'

services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    volumes:
      - ./config/init:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data

  frontend:
    image: node:21-alpine3.18
    tty: true
    volumes:
      - ./full-stack-frontend:/home/node/app
    ports:
      - 5173:5173
    working_dir: /home/node/app
    command: /bin/sh -c "yarn install && yarn dev"

volumes:
  db-store:
