version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./full-stack-backend/Dockerfile
    volumes:
      - ./full-stack-backend:/backend/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: db_name
      TZ: Asia/Tokyo
      ENV_LANG: ja_JP.UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data

  frontend:
    image: node:21-alpine3.18
    tty: true
    volumes:
      - ./full-stack-frontend:/home/node/app
    ports:
      - 5173:5173
    working_dir: /home/node/app
    command: /bin/sh -c "yarn install && yarn dev"

volumes:
  db_volume:
