CREATE TABLE IF NOT EXISTS USERS (
    ID serial primary key,
    NAME text,
    AGE int
);

INSERT INTO USERS (NAME, AGE) VALUES ('Alice', 30), ('Bob', 40);

CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DEPARTMENT_ID serial primary key,
    DEPARTMENT_NAME text,
    REGESTERED_DATE date,
    USER_ID int,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
INSERT INTO DEPARTMENT (DEPARTMENT_NAME, REGESTERED_DATE, USER_ID) VALUES ('総務', '2020-01-01', 1), ('マーケティング', '2020-01-01', 2);